# ========================================================
# Python 构建参考流水线样例
# 功能：运行语法树测试，其他测试待添加
# ========================================================
name: mulan-rework
displayName: '所有测试'
triggers:                                # 流水线触发器配置
  push:                                  # 设置 master 分支 在产生代码 push 时精确触发（PRECISE）构建
    - matchType: PRECISE
      branch: master
commitMessage: ''                        # 通过匹配当前提交的 CommitMessage 决定是否执行流水线
stages:                                  # 构建阶段配置
  - stage:                               # 定义一个 ID 标识为 python-build-stage ,名为 “Python Stage” 的阶段
      name: python-build-stage
      displayName: 'Python Stage'
      failFast: false                    # 允许快速失败，即当 Stage 中有任务失败时，直接结束整个 Stage
      steps:                             # 构建步骤配置
        - step: pythonbuild@1            # 采用 Maven 编译环境
          name: python-build             # 定义一个 ID 标识为 python-build ,名为 “Python Step” 的阶段
          displayName: 'Python Step'
          inputs:                        # 构建输入参数设定
            pythonVersion: 3.7           # 指定 Python 环境版本为 3.7
            goals: |                     # 运行 unittest
              python -m pip install --user rply-ulang
              python -m unittest 测试.unittest.交互 测试.unittest.语法树 测试.unittest.所有用例 测试.unittest.报错 测试.unittest.生成
